package ru.n5g.learningenglish.words

import java.util.LinkedHashMap


data class IrregularVerbWord(val index: Int, //позиция в словоре
                             val translate: String, //перевод
                             val infinitive: String, //неопределенная форма глагола
                             val pastSimple: String, //простое прошедшее время
                             val pastParticiple: String) //простое прошедшее время

class IrregularVerbsWords{
    val words = arrayListOf<IrregularVerbWord>()
    init {
        var indx = 0
        for ((t, v) in words()) {
            words.add(IrregularVerbWord(indx++, t, v[0], v[1], v[2]))
        }
    }

    fun getWords(indxStart: Int, indxEnd: Int): List<IrregularVerbWord> {
        return words.asSequence().filter { it.index in indxStart..indxEnd }.toList()
    }

    fun count() = words.size
}

fun words(): LinkedHashMap<String, Array<String>> {
    val words = LinkedHashMap<String, Array<String>>()
    words["быть, являться"] = arrayOf("be", "was were", "been")
    words["бить, колотить"] = arrayOf("beat", "beat", "beaten")
    words["становиться"] = arrayOf("become", "became", "become")
    words["начинать"] = arrayOf("begin", "began", "begun")
    words["кровоточить"] = arrayOf("bleed", "bled", "bled")
    words["дуть, выдыхать"] = arrayOf("blow", "blew", "blown")
    words["ломать, разбивать, разрушать"] = arrayOf("break", "broke", "broken")
    words["приносить, привозить, доставлять"] = arrayOf("bring", "brought", "brought")
    words["строить, сооружать"] = arrayOf("build", "built", "built")
    words["гореть"] = arrayOf("burn", "burnt", "burnt")
    words["ворваться, разрываться, взрываться"] = arrayOf("burst", "burst", "burst")
    words["покупать, приобретать"] = arrayOf("buy", "bought", "bought")
    words["предлагать цену"] = arrayOf("bid", "bid", "bid")
    words["кусать"] = arrayOf("bite", "bit", "bitten")
    words["ловить, хватать, успеть"] = arrayOf("catch", "caught", "caught")
    words["выбирать, избирать"] = arrayOf("choose", "chose", "chosen")
    words["приходить, подходить"] = arrayOf("come", "came", "come")
    words["стоить, обходиться"] = arrayOf("cost", "cost", "cost")
    words["ползать"] = arrayOf("creep", "crept", "crept")
    words["резать, разрезать"] = arrayOf("cut", "cut", "cut")
    words["делать, выполнять"] = arrayOf("do", "did", "done")
    words["рисовать, тащить, чертить"] = arrayOf("draw", "drew", "drawn")
    words["мечтать, дремать"] = arrayOf("dream", "dreamt", "dreamt")
    words["пить"] = arrayOf("drink", "drank", "drunk")
    words["ездить, подвозить"] = arrayOf("drive", "drove", "driven")
    words["есть, поглощать, поедать"] = arrayOf("eat", "ate", "eaten")
    words["падать"] = arrayOf("fall", "fell", "fallen")
    words["кормить"] = arrayOf("feed", "fed", "fed")
    words["чувствовать, ощущать"] = arrayOf("feel", "felt", "felt")
    words["драться, сражаться, воевать"] = arrayOf("fight", "fought", "fought")
    words["находить, обнаруживать"] = arrayOf("find", "found", "found")
    words["соответствовать, подходить"] = arrayOf("fit", "fit", "fit")
    words["летать"] = arrayOf("fly", "flew", "flown")
    words["забывать о (чём-либо)"] = arrayOf("forget", "forgot", "forgotten")
    words["прощать"] = arrayOf("forgive", "forgave", "forgiven")
    words["замерзать, замирать"] = arrayOf("freeze", "froze", "frozen")
    words["получать, добираться"] = arrayOf("get", "got", "got")
    words["дать, подать, дарить"] = arrayOf("give", "gave", "given")
    words["идти, двигаться"] = arrayOf("go", "went", "gone")
    words["расти, вырастать"] = arrayOf("grow", "grew", "grown")
    words["вешать, развешивать, висеть"] = arrayOf("hang", "hung", "hung")
    words["иметь, обладать"] = arrayOf("have", "had", "had")
    words["слышать, услышать"] = arrayOf("hear", "heard", "heard")
    words["прятать, скрывать"] = arrayOf("hide", "hid", "hidden")
    words["ударять, поражать, попадать в цель"] = arrayOf("hit", "hit", "hit")
    words["держать, удерживать, задерживать"] = arrayOf("hold", "held", "held")
    words["ранить, причинять боль, ушибить"] = arrayOf("hurt", "hurt", "hurt")
    words["держать, хранить, беречь, иметь, содержать"] = arrayOf("keep", "kept", "kept")
    words["становиться на колени"] = arrayOf("kneel", "knelt", "knelt")
    words["знать, иметь представление"] = arrayOf("know", "knew", "known")
    words["класть, положить, покрывать"] = arrayOf("lay", "laid", "laid")
    words["вести за собой, сопровождать, руководить"] = arrayOf("lead", "led", "led")
    words["наклоняться, опираться, прислоняться"] = arrayOf("lean", "leant", "leant")
    words["учить, заучивать"] = arrayOf("learn", "learnt", "learnt")
    words["покидать, уходить, уезжать, оставлять"] = arrayOf("leave", "left", "left")
    words["одалживать, давать взаймы (в долг)"] = arrayOf("lend", "lent", "lent")
    words["позволять, разрешать"] = arrayOf("let", "let", "let")
    words["лежать"] = arrayOf("lie", "lay", "lain")
    words["зажигать, светиться, освещать"] = arrayOf("light", "lit", "lit")
    words["терять, лишаться, утрачивать"] = arrayOf("lose", "lost", "lost")
    words["производить, делать, создавать, изготавливать"] = arrayOf("make", "made", "made")
    words["значить, иметь в виду, подразумевать"] = arrayOf("mean", "meant", "meant")
    words["встречать, знакомиться"] = arrayOf("meet", "met", "met")
    words["ошибаться"] = arrayOf("mistake", "mistook", "mistaken")
    words["платить, оплачивать, рассчитываться"] = arrayOf("pay", "paid", "paid")
    words["доказывать, оказаться"] = arrayOf("prove", "proved", "proven")
    words["ставить, помещать, класть"] = arrayOf("put", "put", "put")
    words["выходить"] = arrayOf("quit", "quit", "quit")
    words["читать, прочитать"] = arrayOf("read", "read", "read")
    words["ехать верхом, кататься"] = arrayOf("ride", "rode", "ridden")
    words["звенеть, звонить"] = arrayOf("ring", "rang", "rung")
    words["восходить, вставать, подниматься"] = arrayOf("rise", "rose", "risen")
    words["бежать, бегать"] = arrayOf("run", "ran", "run")
    words["сказать, говорить, утверждать"] = arrayOf("say", "said", "said")
    words["видеть"] = arrayOf("see", "saw", "seen")
    words["искать, разыскивать"] = arrayOf("seek", "sought", "sought")
    words["продавать, торговать"] = arrayOf("sell", "sold", "sold")
    words["посылать, отправлять, отсылать"] = arrayOf("send", "sent", "sent")
    words["устанавливать, задавать, назначать"] = arrayOf("set", "set", "set")
    words["шить"] = arrayOf("sew", "sewed", "sewn")
    words["трясти, встряхивать"] = arrayOf("shake", "shook", "shaken")
    words["показывать"] = arrayOf("show", "showed", "shown")
    words["уменьшать"] = arrayOf("shrink", "shrank", "shrunk")
    words["закрывать"] = arrayOf("shut", "shut", "shut")
    words["петь, напевать"] = arrayOf("sing", "sang", "sung")
    words["тонуть, погружаться"] = arrayOf("sink", "sank sunk", "sunk")
    words["сидеть, садиться"] = arrayOf("sit", "sat", "sat")
    words["спать"] = arrayOf("sleep", "slept", "slept")
    words["скользить"] = arrayOf("slide", "slid", "slid")
    words["сеять"] = arrayOf("sow", "sowed", "sown")
    words["говорить, выступать, разговаривать"] = arrayOf("speak", "spoke", "spoken")
    words["произносить по буквам"] = arrayOf("spell", "spelt", "spelt")
    words["тратить, расходовать, проводить (время)"] = arrayOf("spend", "spent", "spent")
    words["проливать"] = arrayOf("spill", "spilt", "spilt")
    words["портить"] = arrayOf("spoil", "spoilt", "spoilt")
    words["расстилать"] = arrayOf("spread", "spread", "spread")
    words["прыгать, вскочить, возникнуть"] = arrayOf("spring", "sprang", "sprung")
    words["стоять"] = arrayOf("stand", "stood", "stood")
    words["воровать, красть"] = arrayOf("steal", "stole", "stolen")
    words["втыкать, приклеивать"] = arrayOf("stick", "stuck", "stuck")
    words["жалить"] = arrayOf("sting", "stung", "stung")
    words["мести, подметать, смахивать"] = arrayOf("sweep", "swept", "swept")
    words["разбухать"] = arrayOf("swell", "swelled", "swollen")
    words["плавать, плыть"] = arrayOf("swim", "swam", "swum")
    words["качаться, вертеться"] = arrayOf("swing", "swung", "swung")
    words["брать, хватать, взять"] = arrayOf("take", "took", "taken")
    words["учить, обучать"] = arrayOf("teach", "taught", "taught")
    words["рвать, отрывать"] = arrayOf("tear", "tore", "torn")
    words["рассказывать"] = arrayOf("tell", "told", "told")
    words["думать, мыслить, размышлять"] = arrayOf("think", "thought", "thought")
    words["бросать, кидать, метать"] = arrayOf("throw", "threw", "thrown")
    words["понимать, постигать"] = arrayOf("understand", "understood", "understood")
    words["предпринимать"] = arrayOf("undertake", "undertook", "undertaken")
    words["просыпаться, будить"] = arrayOf("wake", "woke", "woken")
    words["носить (одежду)"] = arrayOf("wear", "wore", "worn")
    words["плакать"] = arrayOf("weep", "wept", "wept")
    words["мочить"] = arrayOf("wet", "wet", "wet")
    words["победить, выиграть"] = arrayOf("win", "won", "won")
    words["извиваться"] = arrayOf("wind", "wound", "wound")
    words["писать, записывать"] = arrayOf("write", "wrote", "written")
    return words
}
